version: "2"
run:
  go: "1.24"
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - wrapcheck
  settings:
    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names: [wg]
    revive:
      rules:
      - name: package-comments
        disabled: true
    godox:
      keywords: [FIXME, BUG]
    ireturn:
      allow: [anon, error, empty, stdlib, generic]
  exclusions:
    generated: strict
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - forcetypeassert
          - funlen
          - goconst
          - lll
          - maintidx
          - gocyclo
          - varnamelen
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - default
        - standard
        - blank
        - dot
  exclusions:
    generated: strict
