package types

import (
	"context"
	"errors"
	"path/filepath"
	"strings"
)

var ErrEmptyOutputPath = errors.New("output path is empty")

//go:generate go tool go-enum --names

// OutputType is the type of CV output being generated by the binary.
// ENUM(pdf, html).
type OutputType string

// OutputGenerator is an interface that each output generator need to implement.
// These generators receive a parsed HTML template and need to generate a proper output.
type OutputGenerator interface {
	Generate(ctx context.Context, content []byte) ([]byte, error)
}

// DetectFileType detects the file type from the file path extension.
// It casts the detected extension to the provided type.
func DetectFileType[C ~string](outputPath string) C {
	ext := strings.Replace(filepath.Ext(outputPath), ".", "", 1)

	return C(strings.ToLower(ext))
}
